# Generated by Django 4.2.30 on 2026-04-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roaster", "0003_alter_blogpost_id_alter_cvanalysis_analysis_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvanalysis",
            name="analysis_data",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="cvanalysis",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="cvanalysis",
            name="overall_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cvanalysis",
            name="processing_time",
            field=models.FloatField(null=True),
        ),
    ]
